### ISSUE TITLE
`inject-sub` support

### ISSUE THREAD

**Issue by dehli** [ferdinand-beyer/refx#5]
Hello, thanks for your time on converting reframe to this library! I've really liked using re-frame w/ helix. I was looking at https://github.com/day8/re-frame/blob/master/docs/FAQs/UseASubscriptionInAnEventHandler.md b/c I would like to have access to a subscription's value within a refx event. Would you be open to having something similar in this library? Not entirely sure how it would look yet, need to do a bit more reading, but wanted to create the issue. Cheers!

**Comment by dehli** [comment]
Thanks @rome-user for the time you took to explain it! I think the two alternatives proposed will definitely be simpler and will work for the cases I'd need this for. I'll go ahead and close this issue then! Cheers :+1:

**Comment by ferdinand-beyer** [comment]
Hey! I see I'm late to the party! :)

I was indeed thinking of a better way to bring subscriptions and event handlers closer together.

In my personal projects, I often try to write functions that operate on the DB, so that they can be used both by subscriptions and event handlers, plus they can be tested easily. In general, I try to stay as much as possible in pure-Clojure-land and don't bind myself to frameworks too much.

However, this approach does not work too well with the subscription graph, i.e. working off a precomputed cached value instead of always starting from the DB. Also sometimes this causes a lot of repetition.

As @rome-user rightfully explained, the challenge here is with the subscription lifecycle and avoiding leaks. One solution I was thinking of is to not clean up subscriptions right away when they have no more listeners, but to keep them around and every now and then "garbage collect" unused listeners. Maybe with a TTL cache, so they can be kept alive if event handlers regularly request them.

Unfortunately I do not have a lot of  time these days to work on refx, so I can't promise anything right now. PRs are welcome however!

**Comment by dehli** [comment]
Wanted to follow up that I created a little helper function that seems to be working great for this. 

```clj
(defn computed-sub
  "Computes a sub's value and then disposes of it.
  Should be used sparingly as it will always be a
  cache miss."
  [sub-props]
  (let [sub (-refx/sub sub-props)
        value @sub]
    (subs/dispose! sub)
    value))
```
