### ISSUE TITLE
[QUESTION]: plans for keeping up-to-date with re-frame?

### ISSUE THREAD

**Issue by jimpil** [ferdinand-beyer/refx#6]
Hi there,

First of all,  thanks for having a go at this - I was also wondering about whether the entire reagent dependency can be dropped from `re-frame` (which I enjoy a lot). 

Do you have any plans around pulling in any `re-frame` advancements periodically (e.g. via a `git rebase` or something), or was the port an one-off thing? For instance, `re-frame` recently introduced the (experimental) notion of a `flow` (see [here](https://day8.github.io/re-frame/flows-advanced-topics/)).  It's nothing ground-breaking, in fact you can achieve the same thing in a variety of ways, however I am curious about whether you plan to 'support' that stuff eventually (including potential bug-fixes).
 
Many thanks in advance :+1:

**Comment by ferdinand-beyer** [comment]
Hi @jimpil! 

Unfortunately I am currently not actively working on `refx`, and since it was not a "clean" form of re-frame, but I actually removed a lot of things (like the tracing code), I don't think it is easy to rebase.

My original idea was actually to get further away from re-frame, and explore some advanced features. I then decided to drop that and start with a version that is closer to re-frame.

However, I am very open to contributions, and/or people willing to take over this project. Maybe it would be feasible to "fork again", and then only replace the subscription bit of the code base... 🤔
